name: DotNetTools CD

run-name: CD for ${{ github.event.pull_request.number }}

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish:
    permissions: read-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Pack NuGet package
        run: dotnet pack DotNetTools/AzureNetIsolatedFunctionMockTools.csproj -c Release

      - name: Publish NuGet package
        run: dotnet nuget push AzureNetIsolatedFunctionMockTools/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.org --skip-duplicate